version: "3.9"
services:
  database:
    container_name: 'ad-spring-server-database'
    image: postgres:15-alpine3.18
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_HOST: localhost
    volumes:
      - database:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4:7.2
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: postgres
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "15432:80"
    depends_on:
      - database
volumes:
  database:
  pgadmin: